### ISSUE TITLE
Add stage_ new_from_clone and stage_new_version Dances

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#118]
#### NOTE: This issue has been renamed and its implementation substantially redesigned since it was initially defined.
The renaming was to necessary to make the new dance names more consistent with the existing _stage_new_holon_ dance. The result of all three dances is a staged holon that is ready to be updated or committed.

The redesign is reflected in the proposal section below.

## Current State

The existing _clone_holon_ and _edit_holon_ methods drag the existing holon's property_map and relationship_map up into the reference layer to do the copying. 

## Proposal

1. Allow both existing and staged holons to be cloned. Only existing holons may have new versions staged.
2. The basic behavior of cloning an existing holon should be pushed down to the Shared Objects (Holon) Layer. The resulting clone will have the same relationship map as the original holon. This means that both the DESCRIBED_BY relationship PREDECESSOR will be copied from the original holon.
3. Responsibility for cleaning up the PREDECESSOR relationship and staging the cloned holon with the CommitManager should be implemented in the Reference layer.

### In holon.rs file

- [x] `clone_holon` should create a new() Holon and then copy the `property_map` and `relationship_map` from the original to the clone.
- [x] rename `edit_holon` to `new_version` and change its implementation. It  should simply call `self.clone_holon()` and then set the cloned holon's `state` to `Changed` before returning

### In holon_reference.rs file

- [x] Rename `clone_holon` to `stage_new_from_clone` method.  This method should delegate the call to its variants. Each variant should return the cloned holon. Next reset PREDECESSOR to none, then  invoke `stage_new_holon` on the commit_manager and then return the staged index of the cloned holon.

### In smart_reference.rs file

- [x] Rename `clone_holon` to `stage_new_from_clone` method. This method should use `get_rc_holon` to get it's holon and then call `clone_holon()` on that holon and return the cloned holon.

- [x] Add a `new_version` method. This method should use `get_rc_holon` to get its holon and then call `new_version()` on that holon.  It should then reset the PREDECESSOR relationship on the cloned holon to refer to the original holon. Next, it should invoke `stage_new_holon` on the commit_manager and then return the staged index of the cloned holon.

### In staged_reference.rs file

- [x] Add a `stage_new_from_clone` method. This method should use `get_rc_holon` to get it's holon and then call `clone_holon()` on that holon and return the cloned holon
### In commit_manager.rs file

- [x] Rename `clone_holon` method to `stage_new_from_clone`
- [x] In the `stage_new_from_clone` method, just delegate this call to the HolonReference. _**Then remove the predecessor**_ , stage the result and return a StagedReference to the new holon.
- [x] Rename `edit_holon` method to `stage_new_version`
- [x] In the `stage_new_version ` method, just delegate this call to the SmartReference. 
       - [ ] add the PREDECESSOR relationship from the cloned holon  to the existing holon 
       - [ ] Then stage the result and return a StagedReference to the new holon.

### Dance Enhancements

_**In the holon_dance_adapter.rs file:**_

To allow existing and staged holons to be cloned, , introduce two DanceTypes:
```
CloneMethod(HolonReference),
NewVersionMethod(HolonId)
```

```
/// *DanceRequest:*
/// - dance_name: "stage_new_from_clone"
/// - dance_type: CloneMethod(HolonReference)
/// - request_body: None
///   
///
/// *ResponseBody:*
/// Index(StagedIndex), // a reference to the newly staged holon
///
```
- [x] Define and implement a new "stage_new_from_clone" dance adapter function.  It should delegate the call to the  HolonReference's `stage_new_from_clone` method

- [x] Implement `build_ stage_new_from_clone_dance_request`  as a Method dance

```
/// *DanceRequest:*
/// - dance_name: "stage_new_version"
/// - dance_type: NewVersionMethod(HolonId)
/// - request_body: None
///   
///
/// *ResponseBody:*
/// Index(StagedIndex), // a reference to the newly staged holon
///
```
- [x] Define and implement a new "stage_new_version" dance adapter function.  It should delegate the call to the `StagedReference::stage_new_version` method

- [x] Implement `build_ stage_new_version_dance_request`  as a CommandMethod dance

_**In the dancer.rs file:**_
- [x] Add "stage_new_version" dance to the Dancer's dispatch table
- [x] Add "stage_new_from_clone" dance to the Dancer's dispatch table

_**In the dance_response.rs file:**_

No changes required.

### Testing _stage_new_from_clone_

The functionality being tested includes cloning from a previously saved holon and cloning from a staged_holon.  

### _Test Goals:_

1. Ensure that `stage_new_from_clone` dance for a **_staged original holon_** returns a successful response and that:
    * the cloned holon's properties match the original holon
    * the cloned holon's relationships match the original holon , EXCEPT that the cloned holon has no PREDECESSOR
2. Ensure that at least one property value can be set and one relationship added to the cloned holon
3. Ensure after commit that both the original and cloned holons have been saved.
4. Ensure that `stage_new_from_clone` dance for a _**previously saved original holon**_ returns a successful response and that:
    * the cloned holon's properties match the original holon
    * the cloned holon's relationships match the original holon , EXCEPT that the cloned holon has no PREDECESSOR
5. Ensure that at least one property value can be set and one relationship added to the cloned holon
9. Ensure after commit that both the original and cloned holons have been saved.

### Test Implementation Notes:

The challenge for testing `stage_new_from_clone` for a _**saved**_ holon and `stage_new_version` is that the holon to clone is not saved (and, therefore, is not assigned a HolonId) until the test is actually executed. So in the test fixture, we don't know the HolonId. But the fixture DOES know the `key`for these holons. I propose the following:

- [x] update the definition of DanceTestState as follows:

```
pub struct DanceTestState {
    pub staging_area: StagingArea,
    // pub created_holons: Vec<Holon>, <-- current definition
   pub created_holons: BTreeMap<MapString,Holon> // <-- proposed definition
}
```

- [x] Update the methods that add to and reference the DanceTestState accordingly.

- [x] change the signature and implementation of `execute_stage_new_from_clone` so that it accepts a `original_holon_ref: TestReference` parameter where:
```
pub enum TestReference {
     SavedHolon(MapString),
     StagedHolon(StagedIndex),
}

```
The `key` can be passed through `SavedHolon` and used to lookup in the _created_holons_ BTreeMap to get the `HolonId` of the saved holon.

Goal 1 can be achieved within a new `test_stage_new_from_clone` test step.
Goal 2 can be achieved via existing `test_with_properties` and `test_add_related_holons` test steps
Goal 3 can be achieved via test_commit and `test_ensure_database_count` and `test_match_db_content` test steps
Goal 4 can be achieved within a new `test_stage_new_from_clone` test step.
Goal 2 can be achieved via existing `test_with_properties` and `test_add_related_holons` test steps
Goal 3 can be achieved via test_commit and `test_ensure_database_count` and `test_match_db_content` test steps

- [x] stage_new_from_clone of StagedHolon passes
- [x] stage_new_from_clone of a previously saved holon passes

### Testing _stage_new_version_

_Test Goals:_

1. Ensure the `stage_new_version` dance for a _**previously saved original holon**_ returns a successful response and that:
    * the cloned holon's properties match the original holon
    * the cloned holon's relationships match the original holon , EXCEPT that the cloned holon's PREDECESSOR relationship refers to the original holon
4. Ensure after commit that both the original and cloned holons have been saved.

- [x] stage_new_version test passes

### Definition of Done

- [x] All tests pass

**Comment by evomimic** [comment]
Questions have arisen about how to handle the `descriptor` and `predecessor` fields when cloning holons. These fields were envisioned as "caches" to facilitate access to holons actually related via relationships. For example, `descriptor` is the HolonReference that is the target of the DESCRIBED_BY relationship and `predecessor` is the HolonReference that is the target of the PREDECESSOR relationship.  

It is unclear whether these fields are actually needed, so perhaps we should just delete them until a clear need has been demonstrated. But if retained, they should be made private and protected by accessor functions (get/set).

**Comment by evomimic** [comment]
In order to test these methods via sweetest, we will first need to expose them as dances (which we were going to need to do anyway). I will update the main description of this issue to include the dance work.

**Comment by dauphin3** [comment]
@evomimic with our newly implemented architecture, should the dance adaptor now be calling the commit manager?

In general, how should the request and response body's change?

**Comment by evomimic** [comment]
@dauphin3 : I pretty significantly revamped the design, but  I think it is ready for you to complete the implementation. Please note the updated description of this issue.

**Comment by dauphin3** [comment]
@evomimic latest commit:  stage_new_from_clone still stuck on ServerError "failed to borrow commit_manager"
not sure why/how this is different from stage_new_holon, because it borrows commit_manager mutably and yet is able to be called multiple times successfully from setup_book_authors

**Comment by dauphin3** [comment]
@evomimic could we just have the commit executor step return the Vec of created_holons ?
this would be useful to get the id directly int the fixture instead of pushing it down to the executor and needing the teststate
