### ISSUE TITLE
Holochain stopped support for nix versions less than 2.20 .. upgrade scripts to use 2.23.x

### ISSUE THREAD

**Issue by nphias** [evomimic/map-holons#130]
UI needs node version >= 20.11.1
seems I dont have PAT workflow scope to update the github workflow.. even in a branch

**Comment by evomimic** [comment]
Would this help?
[Git - Add the workflow scope to your Personal Access Token](https://johnnycase.github.io/post/2021/07/22/git-workflow-access-token.html)

If not... and there is something you think I need to do on my end, let me know.

**Comment by nphias** [comment]
yes thanks
