### ISSUE TITLE
Exactly-One HolonSpace Semantics via Progenitor

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#159]
This enhancement assures that one and only one HolonSpace is created per DHT. It uses the [Holochain Progenitor](https://forum.holochain.org/t/progenitor/1063) pattern and a special `LocalHolonSpace` LinkType. 

## Dependencies

- [x] Issue #3 

## Current State

- `LocalHolonSpace` LinkType has not been scaffolded
- a HolonSpace structure has been defined and various helper methods implemented
- a HolonSpaceManager service has been created that implements:
    - a public `create_local_holon_space` method that stages and commits a HolonSpace within this DHT. **_However, it does NOT anchor it to a "holon_space" path._**
    - a private `fetch_and_set_local_holon_space` method that searches the DHT for the LocalHolonSpace singleton and, if found, sets a reference to it in the context. Otherwise, it returns a HolonError. **_Currently, this method uses a brute force linear search of all holons._**
    - a public `ensure_local_holon_space_in_context` method that can be called from the dancer to check the current context to see if it contains a HolonReference to the LocalHolonSpace and, if not, invokes the private `fetch_and_set_local_holon_space` method. If this method returns an error, then `ensure_local_holon_space_in_context` invokes `create_local_holon_space` to create the local holon space. **_Note that this approach can potentially result in multiple local_holon_spaces being created._**

## Proposal

_**NOTE: We are deferring implementation of the progenitor pattern for now. There seems to be a catch-22 for the first space. We don't know agent public key of the progenitor cell until AFTER the cell has been created. But, by that time, it is too late to set the DNA properties, because the DNA digest has already been written to the DHT.**_

- [x] Scaffold a new `LocalHolonSpace` LinkType
_- [ ] Update the DNA properties for the holons zome to designate a progenitor cell. _(DEFERRED FOR NOW)_
_- [ ] Implement the holons zome's `init()` callback to ensure exactly one local HolonSpace is created per DHT (see below)  _(DEFERRED FOR NOW)__
- [x] Enhance the `create_local_holon_space` method to anchor the created holon space to a "holon_space" path via the `LocalHolonSpace` LinkType.
- [x] Enhance the `fetch_and_set_local_holon_space` method to leverage the "holon_space" anchor to find the LocalHolonSpace, instead of the current brute force approach.
_- [ ] Modify `ensure_local_holon_space_in_context` so that it does NOT attempt to create the local holon space, if `fetch_and_set_local_holon_space` returns an error. Instead, just return the same error.  (DEFERRED FOR NOW)_

### Implementing the Holochain Progenitor Pattern (DEFERRED)
One Cell is designated in the DNA as the _progenitor_.  Once created, HolonSpaces are linked to a special `LocalHolonSpace` LinkType. When the Conductor initializes a cell and calls its `init()` callback:

1. The init() function checks to see if it is there is a HolonSpace anchored to the `LocalHolonSpace` LinkType. 
2. If yes, simply return.
3. Otherwise check to see if the cell whose init() method is being called is progenitor cell (per the DNA properties)
4. If not, simply return. Otherwise, call the `create_local_holon_space` method to create the local holon space and anchor it to the  `LocalHolonSpace` LinkType_

## Testing

- [ ] Ensure  the LocalHolonSpace is successfully created by the designated Progenitor cell
- [ ] Ensure the LocalHolonSpace is NOT created by a non-progenitor cell

If possible, consider approaches to testing the corner cases:

- Progenitor doesn't create more than one LocalHolonSpace
- Dancer in a non-progenitor cell returns an error if it fails to fetch local holon space due to a race condition, where the progenitor has not yet had a chance to create the local holon space.

## Definition of Done

- [ ] progenitor and non-progenitor tests pass
- [ ] All regression tests pass

**Comment by nphias** [comment]
my thoughts on this are that it probably only applies to I-space (your personal devices). 
The way forward might be to use the 'authority pattern' such that each new device checks in with the authoriy node first eliminating any kind of race condition..  In practical terms this would look like i have a device running the app and I want to link other devices.

**Comment by evomimic** [comment]
@nphias:  Here's the dialog I had with Guillem regarding progenitor pattern:

There seems to be a catch-22 for the first use of the progenitor pattern. If I already HAVE a DNA and know the agent_pub_key of the intended progenitor cell, I can clone the DNA and then that key as the progenitor in the DNA properties of the clone. But I don't already have a DHT, I don't know the agent public key of the progenitor cell until AFTER the cell has been created. But, by that time, it is too late to set the DNA properties, because the DNA digest has already been written to the DHT.

One workaround may be to create a DHT for the sole purpose of getting an agent so it can create the DNA of the DHT I really want and set the DNA progenitor property.

Am I missing something here?
Guillem Cordoba — 10/16/2024 3:01 AM
yeah I've been doing this with this admin ws call: https://docs.rs/holochain_conductor_api/0.5.0-dev.0/holochain_conductor_api/enum.AdminRequest.html#variant.GenerateAgentPubKey
[AdminRequest in holochain_conductor_api - Rust](https://docs.rs/holochain_conductor_api/0.5.0-dev.0/holochain_conductor_api/enum.AdminRequest.html)
Represents the available conductor functions to call over an admin interface.
to first generate the key pair and then call installapppayload with that
**Guillem Cordoba — 10/16/2024 3:23 AM**
but that won't work well in holochain v0.4
https://github.com/holochain/holochain/issues/4346
GitHub
[[Feature Request] Can't install apps that require `AgentPubKey`s in...](https://github.com/holochain/holochain/issues/4346)
A really common hApp design pattern is the progenitor pattern. In it, the first agent that installs the app adds their public key as the property of the DNAs in the app. This agent will become the ...
[Feature Request] Can't install apps that require `AgentPubKey`s in...
