### ISSUE TITLE
Add Support for "Changed" State to Holon commit() method

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#20]
Currently, the commit() method only supports the "New" and "Fetched" states. This story adds support for "Changed" state. Doing so requires creating a new version of the HolonNode using the update_holon_node function in holon_node.rs.

A future issue will handle updates to SmartLinks based on relationship map changes.

**Comment by dauphin3** [comment]
@evomimic would we not want commit() to return the ActionHash instead of Self

if fetched, it could return nothing or have some other logic

**Comment by dauphin3** [comment]
Im not sure why a Fetched state would ever be attempted to be committed, perhaps a guard could be placed elsewhere and there is no need for that arm.

Also, wondering if it would be useful to have separate commit fns for new & update

**Comment by dauphin3** [comment]
for the UpdateHolonNodeInput, how to get the original_hash to pass through the commit if not stored in Holon struct? 
should a field be added?

**Comment by evomimic** [comment]
Thanks for the questions @dauphin3 ... here are my responses:

> "@evomimic would we not want commit() to return the Record or ActionHash instead of Self
> if fetched, it could return nothing or have some other logic"

`Record` and `ActionHash` are both Holochain concepts. The Holon object is encapsulating the storage mechanism. This improves evolvability (i.e., simplifies migration to an alternate storage technology) and (of more immediate importance) hides all the complexity of dealing with the storage tier.

Returning the Holon from `commit` allows a sequence of updates to applied and committed (a popular style for some use cases). 

> Im not sure why a Fetched state would ever be attempted to be committed, perhaps a guard could be placed elsewhere and there is no need for that arm... or if reached it should always throw error

Not sure what your concern is or what you think we need to guard against. Not having to worry about whether a Holon has been changed or not is exactly the point of keeping the state in the Holon itself.

> Also, wondering if it would be useful to have separate commit fns for new & update

We're trying to encapsulate complexity, not export it. On what basis would a caller decide which function to call? Forcing the caller to decide which function to call also forces them to keep track of whether the staged holon is new or updated. Better to keep track of that in the Holon itself. This way clients don't have to know or care.

> for the UpdateHolonNodeInput, how to get the original_hash to pass through the commit ?
> should a field be added to Holon struct?

I'm a bit unclear on the difference between original_hash and previous_hash. I'm thinking on of them can be retrieved from the Holon's `saved_node` Record. Can you explain the difference?

**Comment by dauphin3** [comment]
> I'm a bit unclear on the difference between original_hash and previous_hash. I'm thinking on of them can be retrieved from the Holon's `saved_node` Record. Can you explain the difference?

original is the actionhash of the first created entry, the scaffolded code for updates allows you to track the changes amongst updates via links... so either we could change that code, removing it, or add a field: original_create_action_hash into Holon struct

**Comment by evomimic** [comment]
> original is the actionhash of the first created entry, the scaffolded code for updates allows you to track the changes amongst updates via links... so either we could change that code, removing it, or add a field: original_create_action_hash into Holon struct

I think we want to preserve the CRUD UpdateLinks, so I wouldn't remove that logic from the scaffolded code. And if we need to store an extra hash, we can certainly add a field to Holon. 

But that seems very odd -- it would imply everyone else is somehow maintaining that extra field somewhere. And how would you populate it? None of the scaffolded code returns an "original_hash" -- just a Record. So every holochain developer is performing some out-of-band call to retrieve an original hash every time they want to do an update to an entry??? Somethin's fishy here.

Also... I'm not convinced that `original` is the action hash of the first created entry. I think it is more subtle than that. Take a look at the scaffolded `get_holon_node` function. It is used to retrieve an entry given its action hash. But what it actually does is find the latest update starting with its the provided action hash parameter (which is called `original_holon_node_hash`). In effect, the function is saying... give me the action hash of the record from the last time you saw it, and I'll return the latest update linked back to that original hash).

**Comment by dauphin3** [comment]
from the docs:
Many updates can point to a single create/update and continue to accumulate as long as agents
author them against that record. It is up to happ developers to decide how to ensure the tree
branches are walked appropriately and that updates point to the correct record, whatever that
means for the happ.

makes me inclined to think you are right, that original does not necessarily mean the original create but it signifies a single point of where you want the updates linked (which could be the original create, or some later update)

**Comment by evomimic** [comment]
Closing this issue now since Issue #26 has been opened for the remaining TODO
