### ISSUE TITLE
Upgrade Holons TypeAliases to newtype pattern

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#22]
Currently the Holons Zome defines a number of Type Aliases. 
```
type HolonId = ActionHash
type OutboundProxyId = ActionHash
type PropertyName = String
type RelationshipName = String
```
For type safety reasons, the purpose of this issue is to instead apply the newtype pattern for this types.

**Comment by dauphin3** [comment]
fixed in PR #24
