### ISSUE TITLE
Define and Implement PropertyGetters Trait

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#27]
The design of the Holons Coordinator zome includes various encapsulating wrappers on a Holon. For example,

- `Holon` defines a PropertyMap holding values of its properties
- `HolonReference` hides whether a Holon is Local or External and whether or not it has been fetched from the DHT.
- `SmartReference` wraps HolonReference, but also may include values for some of its properties (to allow them to be used without having to retrieve the underlying Holon)

The purpose of this story is:

1. Define a new `HolonGetters` trait 
2. Add a `get_property_value` function to that trait that allows property  values to be retrieved from any of the structures listed above without having to know or care which level of wrapper the caller is accessing
3 Provide implementations of that trait function for `Holon` and `HolonReference` (SmartReference implementation will be done in a later issue).

### Trait

```
pub trait HolonGetters {
     fn get_property_value(&self, property_name:PropertyName) -> Result<Option<BaseValue>, HolonError>;
}
```

### Holon Implementation of HolonGetters trait

Do a lookup in the Holon's `property_map` using the supplied `property_name`.  Return `None` if there is no value for that `property` in the `property_map`.

### HolonReference Implementation of HolonGetters trait

- Use the `get_holon()` function defined in Issue #23 to get the referenced holon
- Delegate the `get_property_value()` call to the referenced holon and return its result

**Comment by dauphin3** [comment]
@evomimic what would be the HolonError case?  Should this trait return just an option instead?
For the Holon case None would be returned if PropertyName does not exist.
For HolonReference, the only error case would be if it was empty, which we will protect against in a later issue.
And it looks like SmartReference would be in the same case scenario.

**Comment by evomimic** [comment]
@dauphin3 ... there are several possibilities:

1. the supplied `property_name` is a valid property_name for the specified Holon, but it currently doesn't have a value. In this case, just return `None`.
2. the supplied 'property_name' is NOT a valid property for the specified Holon, it which case we should return an "Invalid Property Name" error. 
3. the HolonReference implementation relies on get_holon() and it can return an error which should then be returned

NOTE: we will only be able to assess validity when the Holon is linked to its HolonDescriptor. So, for now, we can't distinguish between cases #1 and #2. I'm fine returning None for cases #1/#2 for now. But I'd leave the trait definition as it is due to case #3 and (eventually, case #2).
