### ISSUE TITLE
Introduce Local HolonSpace

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#3]
This enhancement introduces support for the local HolonSpace into MAP Holons. This includes:

1. Introducing a HolonSpace struct and associated helper functions
2. Implementing a HolonSpaceManager service that handles the details of creating and fetching the LocalHolonSpace and setting a reference to it in the `context`. 
3. Overloading the dance() function (for now) to do a "lazy create" of the LocalHolonSpace -- NOTE: this approach will be changed when we implement Issue #159  )
4. Introducing a SessionState structure via Issue #158 that separates out the state information we want to ping-pong between client & guest on every dance request/response from the fields that are specific to the request/response. 
5. Adding a HolonRerence to the LocalHolonSpace to _SessionState_ and _HolonsContext_ 

Support for space proxies will be added in a later issue. See [MAP Holon Spaces wiki](https://github.com/evomimic/map-holons/wiki/Map-Holon-Spaces) for the design concept.

# Dependencies

- [x] Issue #142 

# Current State

# Proposal

![image](https://github.com/user-attachments/assets/cbca4801-cd96-41ff-a1df-451ba82c689a)

### In the commit_manager.rs file

- [ ] add an `is_completed` helper method to CommitResponse
- [ ] add a `find_local_id_by_key` helper method that searches through CommItResponse's saved_holons vector for a holon matching the specified key
- [ ] 

### Create a new holon_space.rs file

- [x] Add a HolonSpace struct using the _[new type pattern](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://doc.rust-lang.org/rust-by-example/generics/new_types.html&ved=2ahUKEwjKyNHVmJ-IAxWlATQIHZraGHgQFnoECAoQAQ&usg=AOvVaw0Ams5kVWE_GnI0rmX9HFTu)_ -- i.e., as a simple tuple struct: 
`pub struct HolonSpace(pub Holon);`

- [x] Implement `new` and `into_holon` functions for HolonSpace
- [x] Implement getters and setters

### Create a holon_space_manager.rs file
This file offers holon space related services:
- [x] Implement public `create_local_holon_space` method that stages and commits a HolonSpace within this DHT
- [x] Implement public `ensure_local_holon_space_in_context` method that ensure a reference to the LocalHolonSpace is included in the context, fetching it from the persistent store or creating it, if necessary.
- [x] Implement private `fetch_and_set_local_holon_space` method that fetches the holon space holon from the persistent store and sets a reference to in the context.

### In the context.rs file

- [x] Add a `local_holon_space: HolonReference` field to the HolonsContext struct and add as a parameter to `init_context`
- [x] Add get/set methods for local_holon_space

### In the smart_reference.rs file

- [ ] Add a `new_from_id` constructor that creates a new SmartReference from a HolonId

### In the core_schema_types/core_schema_type_names.rs file

- [x] Add _CoreSchema_ and _CoreSchemaFor_ as variants for the _CoreRelationshipTypeName_ enum

### In the relationship_type_loader.rs file

- [x] Add definitions for the CoreSchema and CoreSchemaFor relationship types to the `get_relationship_type_loader `function:
```
CoreSchemaFor => RelationshipTypeLoader {
                descriptor_name,
                description : MapString(
                    format!("Specifies the HolonSpace(s) for which this Schema is used to create instances of L0 types.")
                ),
                label,
                described_by: None,
                owned_by: HolonReference,
                relationship_type_name,
                source_owns_relationship: MapBoolean(true),
                deletion_semantic: DeletionSemantic::Allow,
                load_links_immediate: MapBoolean(false),
                target_collection_type: CollectionTypeSpec{
                    semantic: CollectionSemantic::SingleInstance,
                    holon_type: CoreHolonTypeName::HolonSpaceType,
                },
                has_inverse: Some(CoreSchema), 
            },
CoreSchema => RelationshipTypeLoader {
                descriptor_name,
                description : MapString(
                    format!("Specifies the (single) Core Schema used to create instances of L0 types within this HolonSpace.")
                ),
                label,
                described_by: None,
                owned_by: HolonReference,
                relationship_type_name,
                source_owns_relationship: MapBoolean(false),
                deletion_semantic: DeletionSemantic::Allow,
                load_links_immediate: MapBoolean(false),
                target_collection_type: CollectionTypeSpec{
                    semantic: CollectionSemantic::SingleInstance,
                    holon_type: CoreHolonTypeName::SchemaType,
                },
                has_inverse: None, // Should be None because `source_owns_relationship` is `false`

            },
```

## Dance Enhancements
The DanceRequest and DanceResponse structures were updated to reference SessionState (including local_holon_space) via Issue #158 .

### In the descriptor_dance_adapter.rs file

- [x] Enhance the build_xxx functions to use session_state

### In the holon_dance_adapter.rs file

- [x] Enhance the build_xxx functions to use session_state

### in the dancer.rs file

- [x] In the dance() function, use `init_context_from_state` to initialize the HolonsContext from SessionState
- [x] In the dance() function, use `restore_session_state_from_context` to restore the SessionState before returning from dance()
- [x] Create a HolonSpaceManager and use `ensure_local_holon_space_in_context` to ensure a local_holon_space reference is populated in context
- [ ] 

# Testing

- [x] In dance_fixtures.rs: Adjust the approach to ensuring database count to allow for Local_holon_space being automatically added.
- [x] descriptor_dance_fixtures.rs: Adjust the approach to ensuring database count to allow for Local_holon_space being automatically added.
- [ ] Adjust all test_xxx_ functions to use session state instead of staging_area

No new test cases required.

# Definition of Done

- [x] All tests cases pass
- [x] Merge conflicts have been resolved

**Comment by evomimic** [comment]
@nphias : The definition of this enhancement is complete enough for you to start development on the native functionality when you have some cycles. I've left the Dances layer design open until you and I have had a chance to discuss how best to match this up with your Stores concept.

**Comment by nphias** [comment]
In the core_schema_types/core_schema_type_names.rs  doesnt seem to exist?

**Comment by evomimic** [comment]
> In the core_schema_types/core_schema_type_names.rs doesnt seem to exist?

Sorry... I renamed it in a later branch that hasn't been merged yet. In your branch, the file is named _core_schema_types_.rs

**Comment by nphias** [comment]
> > In the core_schema_types/core_schema_type_names.rs doesnt seem to exist?
> 
> Sorry... I renamed it in a later branch that hasn't been merged yet. In your branch, the file is named _core_schema_types_.rs

CoreRelationshipTypeName enum is not in that file either.. should i create it?

**Comment by evomimic** [comment]
> CoreRelationshipTypeName enum is not in that file. Its in relationship_type_loader.rs .. assume you mean that one
Correct.
