### ISSUE TITLE
Set up Validation Approach

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#39]
This issue frames in the shared validation architecture and does the checks possible without a descriptor being available.

Validation design is documented in the [Validation Strategy Wiki page](https://github.com/evomimic/map-holons/wiki/Validation-Strategy).

### Definition of Done:

- [x] ValidationState Enum defined and added to Holon and RelationshipTarget
- [x] Define ValidationError Enum
- [x] Wrap ValidationError in HolonError
- [ ] Frame out the validation lifecycle logic -- only as far as  NoDescriptor state

**Comment by owleyeview** [comment]
I added some detail to the Validation-Strategy wiki page.

@evomimic: Please review and let me know if I'm getting anything wrong.

**Comment by evomimic** [comment]
I approved and merged the PR for this branch. Closing issue.
