### ISSUE TITLE
Refactor holon_api

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#63]
## Background and Motivation
The current `holon_api` exposes the following as `hdk_extern` functions :
```
pub fn get_all_holons( _: (),) -> ExternResult<Vec<Holon>>
pub fn get_holon(id: HolonId,) -> ExternResult<Option<Holon>>
pub fn new_holon(_:()) -> ExternResult<Holon>
pub fn with_property_value(input: WithPropertyInput) -> ExternResult<Holon> 
pub fn commit(input: Holon) -> ExternResult<Holon>
pub fn delete_holon(target_holon_id: ActionHash,) -> ExternResult<ActionHash>
```
The with_property_value function takes the following input parameter:
```
pub struct WithPropertyInput {
    pub holon: Holon,
    pub property_name:PropertyName,
    pub value: BaseValue,
}
```

This API is inconsistent with the new design that uses the CommitManager to manage shared state:

1. It doesn't maintain CommitManager state (affects ALL current API functions) 
2. `with_property_value` passes the holon directly via its input parameter instead of via a StagedReference to the Holon being updated  and it relies on Holon implementing the `clone()` method which is no longer supported
3. `commit` operates on an individual holon instead of comitting the entire staged state all at once.
4. `delete_holon` actually _performs_ the delete instead of _staging_ the holon for deletion upon commit.
5. it doesn't facilitate client-side holon caching. For example, get_all_holons ALWAYS returns fully inflated holons instead of just SmartCollections.

## Proposed Resolution

Item 1 is the focus of Issue #43. If we assume it will take care of passing the StagingArea back and forth with StagedReferences represented via indexes into the StagingArea vector, then:

- the `WithPropertyValueInput` struct can use a `StagedReference` instead of `Holon`. 
- `get_all_holons` can be changed to return a vector of `Holonids`
- `new_holon` can be renamed to stage_new_holon and return a StagedReference
- `delete_holon` can be changed to just to stage a holon for deletion
- `commit` can be changed to be offered by the CommitManager and take no arguments.

## Definition of Done
The following test cases all pass:

- [ ] **Simple Create Holons**
  - [x] Ensure database is empty
  - [x] Stage New Holon -- for a book holon
  - [x] Stage New Holon -- for a Person holon
  - [x] commit
  - [ ] match database content -- ensure Book & Person Holon exist and their properties match expected values
 
- [x] **Stage, Add Properties, Commit, Delete Holons**
  - [x] Ensure database is empty
  - [x] Stage New (empty) Holon -- for a book holon
  - [x] add "title" property
  - [x] add "description" property
  - [x] Stage New (populated) Holon -- for a Person holon
  - [x] commit
  - [ ] match database content -- ensure Book & Person Holon exist and their properties match expected values
  - [ ] stage_delete Person
  - [ ] commit
  - [ ] stage_delete book
  - [ ] commit
  - [ ] ensure database is empty

- [ ] **Add Related Holons**

  - [ ] Ensure database is empty
  - [ ] Stage New Holon -- for a book holon
  - [ ] Stage New Holon -- for a Person holon
  - [ ] Stage New Holon -- for an additional Person
  - [ ] Add "AUTHORED_BY" relationship from book to both persons
  - [ ] commit
  - [ ] match database content -- get the book Holon and ensure it matches expected,  get its AUTHORED_BY relationship. and ensure it returns the expected Persons, ensure each Person 'sproperties match expected.
  - [ ] stage_delete Person
  - [ ] stage_delete the other Person
  - [ ] commit
  - [ ] stage_delete book
  - [ ] commit
  - [ ] ensure database is empty

**Comment by dauphin3** [comment]
fixed the "wrong msgpack marker Null" error by changing DanceTestStep::Commit() to a unit variant DanceTestStep::Commit since there is no associated data
