### ISSUE TITLE
Create SmartLinks on Commit (relationship_name only)

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#65]
As part of the commit flow, we need to create SmartLinks in holochain. Until we have RelationshipDescriptors, these SmartLinks will need to encode relationship_name. This will need to be passed as a parameter through the commit chain starting with RelationshipTarget.

This enhancement also includes creating a `smart_link_manager.rs` within the holons zome and implementing :
` create_smart_link(from_address: HolonId, to_address: HolonId, relationship_name: RelationshipName)->Result<(),HolonError>`

This function should encode relationship_name into LinkTag and then invoke the hdk's create_link function to add the link and convert any error returned into a HolonError.

- [x] add `smartlink_manager.rs` and implement it's `create_smartlink` function
- [x] Edit Holon's commit method so that when it calls commit on each RelationshipTarget in its relationship_map, it passes relationship_name (in addition to the source_id it is already providing)
- [x] Edit RelationshipTarget::commit to accept relationship_name  and pass it along to editable_collection's commit
- [x] Edit StagedCollection::commit to accept relationship_name  and pass it along to holon_reference's commit
- [x] Implement HolonReference::commit(&self, context, source_id, relationship_name: RelationshipName)->Result<(),HolonError>
- [x] If it's variant is Staged, then first call commit() on its referenced holon and use its holon_id as the to_address on a  call create_smart_link()
- [x] If it's variant is SmartReference, then just call  create_smartlink()

### Definition of Done:

- [x] All of the above changes are implemented and compile successfully... sweetest is not required

**Comment by dauphin3** [comment]
commit_manager.rs line 160 there is an error now calling commit due to missing context and I wasn't sure how to handle that.

since api is changing, I commented out the extern commit.

for SmartLinkInput, I left the the optional field commented out for now, I don't see a need to handle the None cases just yet. Left some todos in a framework for building the linktag.

put header and seperator const's in integrity zome in smartlink file.

**Comment by evomimic** [comment]
- I added context as parameter for commit_manager's commit so it could delegate that through.
- Enhanced StagedReference's commit to create the return the HolonId of the committed Holon
- Enhanced HolonReference's commit so that after committing the StagedReference it creates a SmartLink
- Everything compiles... I pushed changes and will create PR

**Comment by evomimic** [comment]
completed and merged
