### ISSUE TITLE
Basic Tryorama Tests

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#78]
Implement client-side tests (via Tryorama) that exercise the Uniform API and match the current set of guest-side tests (via `rpm run sweetest`).

### Background
This issue tests the following dances currently offered by the Uniform Test API. 

- get_all_holons (Standalone)
- stage_new_holon (Standalone)
- with_properties (Command)
- commit (Standalone)

The holon_dance_adapter.rs file includes "build_xxx" functions that build (guest-side) DanceRequest objects for each of the dances offered by the Holons zome. For Tryorama, we will need similar client-side DanceRequest builders.

Test cases are composed from test steps.

## Definition of Done
The following test cases all pass:

- [x] **Test Case 1: Stage, Add Properties, Commit Holons**
  - [x] Ensure database is empty
  - [x] Stage New (empty) Holon -- for a book holon
  - [x] add "title" property
  - [x] add "description" property
  - [x] Stage New (populated) Holon -- for a Person holon
  - [x] commit
  - [x] match database content -- ensure Book & Person Holon exist and their properties match expected values

**Comment by nphias** [comment]
created a new branch from main.. updated tryorama tests .. using the universal API. .. get_all_holons works .. Work in progress

**Comment by nphias** [comment]
test 1 is done and committed .. continuing with 2 and 3 when the api is ready

**Comment by evomimic** [comment]
I'm reviewing the PR for abandon changes right now.
