### ISSUE TITLE
Unify PortableReference into HolonReference

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#89]
When shipping references to staged and saved holons back and forth between client and guest, we introduced a PortableReference data type. This enhancement makes some adjustments to StagedReference and SmartReference to allow HolonReference to be used as a portable reference type and eliminate the need for a separate PortableReference structure.

Currently SmartReference and StagedReference includes keys, but there doesn't seem to be a compelling reason for that.  Their underlying holons provide access to their keys via` get_key` methods.This enhancement drops key fields from both.

## Proposal

- [x] Drop the `key` field and `rc_holon` fields from the definition of SmartReference
- [x] Clean up references to the key field in constructors/builders
- [x] Adjust implementations so that attempts to retrieve `rc_holon` from a SmartReference are delegated to `get_rc_holon` calls on the cache. The `ensure_rc_holon` function can be dropped.  Calls an ensure_rc_holon should be replaced with calls on the cache_manager's `get_rc_holon` -- as should any attempts to access the SmartReference's (now-deleted) `rc_holon` field directly.
- [x] Drop the `key` field from the definition of StagedReference
- [x] Clean up references to the key field in constructors/builders
- [x] Replace uses of PortableReference with HolonReference

### Testing
Ensure no loss of existing functionality by running regression tests:
- [ ] Ensure dance_test fixtures are setting the key field manually on all "Book" holons (but not "Person" holons) they are including in a test case

### Definition of Done

- [ ] All sweetests pass

**Comment by dauphin3** [comment]
@evomimic there is no way to set the key in the stage_new_holon dance and therefore unable to match on expected from responsebody.staging_area

how best to proceed for implementing set_key_manually in tests?

**Comment by evomimic** [comment]
When you  create a holon in the dance_fixture, you can call the `set_key_manually` method to set the key on the holon.
