### ISSUE TITLE
Implement RemoveRelatedHolons Dance

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#95]
## Summary

This enhancement adds the "_**remove_related_holons**_" dance to the Uniform API. This dance is a CommandMethod that stages (but does not commit) removal of one or more holons (specified by their HolonReferences) from the specified `relationship_name` for the specified source holon.  As a result of this dance, the `editable_collection` within the RelationshipTarget for the specified relationship should be modified to reflect the removal of the specified holons. 

### Dependencies

None

## Current State of Native Functionality:

- There is no functionality implemented that supports removing holons from a staged relationship.

## Proposal

For reference, I've included a diagram illustrating the Uniform API architecture. 

![image](https://github.com/user-attachments/assets/3a2b79c3-b530-422a-8b37-26f35da7bf62)

### Enhance Native Functionality 

**_In the staged_reference.rs file:_**

- [x] Implement a new _remove_related_holons_ method:

```
pub fn remove_related_holons(  
    &mut self,  
    context: &mut HolonsContext,   
    relationship_name: RelationshipName,
    holons: Vec<HolonReference>,  
 
) -> Result<Self, HolonError>
```

  _HINT: Use the implementation of `add_related_holons` as a template._

  - Get the `editable_collection` for the _RelationshipTarget_ in the source staged_holon's `relationship_map` corresponding to the specified `relationship_name`.  
      - Return `InvalidRelationship` error if the source holon's relationship_map does not contain an entry for the specified `relationship_name`.  If the source holon doesn't have a descriptor,  use `Unknown` for the HolonType
  - Iterate through the supplied `holons` and, if a matching reference is found in the collection, remove it from the collection. If not found, just skip it. 

### Dance Enhancements

_**In the holon_dance_adapter.rs file:**_

```
/// *DanceRequest:*
/// - dance_name: "remove_related_holons"
/// - dance_type: CommandMethod(StagedIndex) -- identifies the holon that is the `source` of the relationship being navigated
/// - request_body:
///     TargetHolons(RelationshipName, Vec<HolonReference>),
///
/// *ResponseBody:*
/// - Index(StagedIndex) -- index for the staged_holon for which related holons were removed
///   
///
```
- [x] Add a new `build_remove_related_holons_dance_request` function 
- [x] Implement a new `remove_related_holons_dance` dance function  
This dance uses the commit_manager's `to_staged_reference` method to get a StagedReference to the source holon. Then invokes the (new) `remove_related_holons` method on that staged_reference.

_**In the dancer.rs file:**_

- [x] Add "remove_related_holons" dance to the Dancer's dispatch table

_**In the dance_response.rs file:**_

- [x] Change the mapping of the `InvalidRelationship` HolonError to the `BadRequest` response code.

### Sweetest Testing Enhancements

_**implement a new test_remove_related_holons.rs file:**_

- [x] Implement "execute_remove_related_holons" test step executor that asks the conductor to "dance" the "remove_related_holons" dance and checks that the response matches the expected response.

_**In the test_data_types.rs file:**_

- [x] Add a RemoveRelatedHolons(StagedIndex, RelationshipName, Vec<HolonReference>, ResponseStatusCode) variant in the `DanceTestStep` enum definition
- [x] add its fmt::Display implementation
- [x] implement the `add_remove_related_holons_step` function:

_**In the dance_fixture.rs file:**_
- [x] Extend the existing `simple_add_related_holons_fixture`  so that it also tests `remove_related_holons`
    - [x] Add a few additional relationships using existing _add_related_holons_ test steps.
    - [x] Prior to `commit`,
         - [x]  add a _remove_related_holons_test_step_  with an invalid source_index. Expect NotFound response code with a HolonNotFound error.                   
         - [x]  add a _remove_related_holons_test_step_  from one of the staged holons using an **invalid** `relationship_name`, expect a `BadRequest` response code with an `InvalidRelationship` error. 
         - [x] add a  _remove_related_holons_test_step_ that removes a single holon from a populated relationship. Expect OK.
         - [x] add a _remove_related_holons_test_step_  that removes several holons from a populated relationship. At least one of those holons should be the holon removed in the prior step (this tests that already removed holons are simply ignored). Expect an OK response.
 
_**In the dance_tests.rs file:**_
- [x] Add a match for the  `DanceTestStep::RemoveRelatedHolons` step that dispatches the `execute_remove_related_holons` function

### Tryorama Tests

- [ ] Extend the client-side test cases to exercise the `remove_related_holons` dance.

## Definition of Done:
- [ ] After extending the  `simple_add_related_holons_fixture` as noted above,  sweetest case **passes** 
- [ ] After extending Tryorama test cases to test this functionality, the new/revised test case **passess**
- [ ] Regression Tests:
       - [ ] All existing sweetest cases pass
       - [ ] All existing tryorama test cases pass

**Comment by evomimic** [comment]
To be complete, we should test that AFTER commit the source holon does NOT have relationships populated for the related holons that were removed. But this requires the `get_related_holons` dance which not available until Issue #84 is completed.

**Comment by evomimic** [comment]
@nphias : It recently became clear that all operations on holon should be implemented in the _Shared Objects layer_, not the _Reference Layer_ of the guest-side architecture.

![image](https://github.com/user-attachments/assets/417cc124-c577-4555-b1e0-9d6850f78742)

This means that StagedReference should just delegate the calls on `add_related_holons` and `remove_related_holons` to their referenced holon and that the bulk of the implementation of those methods should be moved to Holon.

Is it possible to make this change in this Issue?

**Comment by nphias** [comment]
tryorama tests left for another issue.. as mutiple api changes .. restructure needed
